### ISSUE TITLE
1) should have valid HTML : test failed

### ISSUE THREAD

**Issue by Ab1d** [zen-audio-player/zen-audio-player.github.io#98]
i have forked the repo in to my local and ran "npm tests", this is the error i am getting.

1) index.html should have valid HTML:
     Uncaught TypeError: Cannot read property 'messages' of undefined
      at test/html-check.js:13:34
      at Request._callback (node_modules/html5-lint/html5-lint.js:86:14)
      at Request.self.callback (node_modules/html5-lint/node_modules/request/request.js:198:22)
      at Request.<anonymous> (node_modules/html5-lint/node_modules/request/request.js:1035:10)
      at IncomingMessage.<anonymous> (node_modules/html5-lint/node_modules/request/request.js:962:12)
      at endReadableNT (_stream_readable.js:905:12)

**Comment by shakeelmohamed** [comment]
Thanks for the report @Ab1d, it looks like the [HTML validation server](https://html5.validator.nu/) used by `html5-lint` is down.

**Comment by shakeelmohamed** [comment]
Digging deeper, apparently this [service has been shut down completely](https://bugzilla.mozilla.org/show_bug.cgi?id=763804#c32)!
